### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by bryanjamesmiller** [boussadjra/laravel-vue-3-starter#1]
@boussadjra - Thanks for putting together this repo!  

Unfortunately, I did encounter one of the errors I was getting the other day.  After running `npm install`, I then ran `npm run development` and I got this output, which I tried googling around to debug but did not have any luck:

```
npm run development

> @ development /Users/bryanmiller/dev/apps/laravel-vue-3-starter
> mix

[webpack-cli] /Users/bryanmiller/dev/apps/laravel-vue-3-starter/node_modules/laravel-mix/src/Log.js:5
    static testing = false;
                   ^

SyntaxError: Unexpected token =
    at new Script (vm.js:79:7)
    at NativeCompileCache._moduleCompile (/Users/bryanmiller/dev/apps/laravel-vue-3-starter/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/bryanmiller/dev/apps/laravel-vue-3-starter/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/bryanmiller/dev/apps/laravel-vue-3-starter/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/bryanmiller/dev/apps/laravel-vue-3-starter/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:1:73)
```

If you have any ideas, I would be very grateful.  Thanks again for putting this together!!  

Actually, the .vue file did compile despite this error, so perhaps the current state is good enough, despite these warnings.  However, I probably can't make the move to Vue 3 until this kind of error doesn't occur as it seems a bit too risky still.  Getting close for sure!

**Comment by boussadjra** [comment]
In my machine it compiles fine :

![image](https://user-images.githubusercontent.com/11801238/97777853-2cb23e80-1b73-11eb-8213-1c72606189cf.png)

I think your issue is related to the cache, composer , the node/npm version or laravel-mix6.

try to raise this issue in laravel mix 6, clean the cache and update your config to the last versions.

**Comment by bryanjamesmiller** [comment]
Thanks for the additional info @boussadjra - I'm on a mac with npm 6.4.1 and node 10.14.2, composer 2.02 and php 7.4.9 - not sure if any of that sheds light on the situation, but I'll probably bug Jeffrey about this next.  Thanks again!!

**Comment by boussadjra** [comment]
I had been having the version 10 of node some months ago and i faced such weird issues but after upgrading to v12 the issues was solved, so try to upgrade

**Comment by besrabasant** [comment]
I tested this on ubuntu. I had the same issue while using node 10.x.x. The issue was resolved after upgrading to node 12.x.x.
